---
start_line: 10
end_line: 20

start_time: 22.09.2023-15:37:04:000 # Not working now
end_time: 22.09.2023-15:37:08:000 # Not working now

log_types:
  debug_log:
    level: DEBUG
    regexp: .*(?P<timestamp>\d{2}\.\d{2}\.\d{4}-\d{2}:\d{2}:\d{2}:\d{3})\s*(?P<labels>\|.*DEBUG.*\|)(?P<content>.*)

  info_log:
    level: INFO
    regexp: .*(?P<timestamp>\d{2}\.\d{2}\.\d{4}-\d{2}:\d{2}:\d{2}:\d{3})\s*(?P<labels>\|.*INFO.*\|)(?P<content>.*)

  error_log:
    level: ERROR
    regexp: .*(?P<timestamp>\d{2}\.\d{2}\.\d{4}-\d{2}:\d{2}:\d{2}:\d{3})\s*(?P<labels>\|.*ERROR.*\|)(?P<content>.*)

  warning_log:
    level: WARNING
    regexp: .*(?P<timestamp>\d{2}\.\d{2}\.\d{4}-\d{2}:\d{2}:\d{2}:\d{3})\s*(?P<labels>\|.*WARNING.*\|)(?P<content>.*)

relations:
  info_log:
    - debug_log
    - error_log
    - warning_log
...

